// <auto-generated />
// Source: simul/flutter_app/lib/game/market_corpus_calendar.dart
// Generated by Tools/GenerateSimulMarketCalendar.ps1. Do not edit by hand.
namespace FamilyCompany.Simulation.Market
{
    internal static class MarketTradingCalendarCorpus
    {
        internal const int TradingDateCount = 6545;
        internal const string SourceSha256 = "C04CCDC5EB57782B785D5B55A5C58A0035598B4D9E07D8A2064E2798D519DB41";
        internal const string Base64 = "z+fzeXw+n83n8/lsLp+P4/L5fDqfz+fz8Xw+n87n88F8Pp3P5/P5fD6fz+cj8Hw+kc/n87l8Pp/P5fP5dD6fz2fz+Xw+n87n89l8Pp/P54P5fD6fz+fz+Xw+Hc7n8/l8MJ/H5/P5PD6fz+bz+Xwul8/H89l8Pp/L5/P5PD6Xz+fz+Xw+n8/nssl8Pp/H5/P5fD6fz+fz+Vwsn8/n8fl8Pp/L5/N5fD6fwefz+Hw+n8/n8/l8PpfJ5zP4fD6fj+fz+Xw8l89n8/lsPp/P5/P5fD6fz+fz+Xw+mM/n8/l8Pp/P5/N5fD6fzyfy+XQ+n8+n8/l8Lp/P5+P5fD6fz+fz+Xg+n8/H8/F8Pp/P5/P5fD6fx+fz+Xg+n8/m8/l8Pp/Px/H5fDadz+fz+Xg+n0/n8/l8Pp/C5/P5fD6fz+fzcXg+n8/n8/FcPp/P5/P5fDqfz+Wz+Xw+n0/n8/lsPp/P54PZfD6fz+fz+Xw+mw7n8/l8Bp/P5/P5fD6bz+fi8Xw+j8/n8/l8Pp/P4/P5fDyfx+fz+Xw+n8/n87lMPp8P5/P5fD6fz+fz+Xwenc/n8/l8Pp/P5/P5fD6fz+fzeXw+n8/n8/l8Pp/H4fP5fD4fz8fz+Xw+n8/ns/k8PpvP5/P5fD6fz+fz+Xw+kc/n8/l8Pp/P5/P5PD6fz2fw+Xw6n8/n8/l8PpfO5/PxfD6fz+fz+Xw8n8+H8/l4Pp/P5/P5fD6fz+Pz+XA+n8/n8vl8Pp/N59P5fD6ezefz+Xw+n89n8/l8Pp+P5vP5fD6fz+fz2XQ4n8/n8/F8Hp/P5/P5fD6bz+PzuXw+n8/n8/l8Lp/P5zP4XDafz+fz+Xw+n88m8/l8Dp/P5/P5fD6fz+dz4Xw+n8Xn8/l8Pp/P5/H5fDCfz+Py+Xw+n8/n8/lcJp/P5/P5DD6fz+fz+Xw+j87n4/l8Pp/P5/P5fB6fz+fz+XAen8/n8/l8Pp/P4/D5fD4fzOfT+Xw+n8/m8zl8Pp+P5/P5fD6fz+fj+Xw+g8/H8/l8Pp/P5/P5fB6fz+fh+Xw+m8/n8/l8Ph9F5/P5dD6fz+fz+Xw+nc/n8/l8AJ7P5/P5fD6fz8fh+Xw+n8/hc/l8Pp/P5/PpeD6dz2bz+Xw+n8/ns/l8Pp8PZtP5fD6fz+fz+Xw6nM/n88F8Po/P5/P5fD6fjefz+Vw+n8/n8/l8PpfP53P4fC6bz+fz+Xw+n89nk/l8Hp7P5/P5fD6fz2fzOXQ+n8/n8/l8Pp/P5/PxfD6fz2fw+Hw+n8/n8/l8HofP5/P5HD4fz+fz+Xw+n8/ms/l8Pp/P5/P5fD4fz+fz+WA+Hs/n8/l8Pp/P5/P4fD4fzOfz6Ww+n8/n8/lcPp/PxvP5fD6fz+fz8Xw+D8/n4/F8Pp/P5/P5fD6Pz+fD+Xw+n83n8/l8Pp+P4/P5eDqfz+fz+Xw+n87n8/l8DhzP5/P5fD6fz+fj8Hw+n8/D83l8Pp/PZ/P5bDybz+fy+Xw+n8/n87l8Pp8P5lPZfD6fz+fz+Xw+m8zn84F8Pp+P5/P5fD6fz4Xz+Xwan8/n8/l8Pp/H5/P5fD4PyOfz+Xw+n8/nc5l8Pp/P54P5eD6fz+fz+Tw6n49n8/l8Pp/HAw==";
    }
}