param(
    [string]$SimulRoot = 'C:\Users\godho\Documents\Codex\simul',
    [string]$OutputPath = ''
)

$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $projectRoot 'Assets\FamilyCompany\Simulation\Market\MarketTradingCalendarCorpus.g.cs'
}

$sourcePath = Join-Path $SimulRoot 'flutter_app\lib\game\market_corpus_calendar.dart'
if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "SIMUL calendar source is missing: $sourcePath"
}

$sourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
$raw = Get-Content -LiteralPath $sourcePath -Raw -Encoding UTF8
$matches = [regex]::Matches($raw, "'(?<date>\d{4}-\d{2}-\d{2})'")
$dates = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
foreach ($match in $matches) {
    [void]$dates.Add($match.Groups['date'].Value)
}

$first = [datetime]'2000-01-04'
$last = [datetime]'2026-07-23'
if (-not $dates.Contains('2000-01-04') -or -not $dates.Contains('2026-07-23')) {
    throw 'SIMUL calendar boundaries changed.'
}
if ($dates.Count -ne 6545) {
    throw "SIMUL calendar date count changed: $($dates.Count)"
}

$dayCount = ($last - $first).Days + 1
$bytes = New-Object byte[] ([math]::Ceiling($dayCount / 8))
foreach ($dateKey in $dates) {
    $date = [datetime]::ParseExact(
        $dateKey,
        'yyyy-MM-dd',
        [System.Globalization.CultureInfo]::InvariantCulture)
    $index = ($date - $first).Days
    if ($index -lt 0 -or $index -ge $dayCount) {
        throw "SIMUL calendar date is outside the declared range: $dateKey"
    }
    $byteIndex = $index -shr 3
    $bitIndex = $index -band 7
    $bytes[$byteIndex] = $bytes[$byteIndex] -bor (1 -shl $bitIndex)
}

$encoded = [Convert]::ToBase64String($bytes)
$generated = @"
// <auto-generated />
// Source: simul/flutter_app/lib/game/market_corpus_calendar.dart
// Generated by Tools/GenerateSimulMarketCalendar.ps1. Do not edit by hand.
namespace FamilyCompany.Simulation.Market
{
    internal static class MarketTradingCalendarCorpus
    {
        internal const int TradingDateCount = $($dates.Count);
        internal const string SourceSha256 = "$sourceHash";
        internal const string Base64 = "$encoded";
    }
}
"@

$directory = Split-Path -Parent $OutputPath
[System.IO.Directory]::CreateDirectory($directory) | Out-Null
[System.IO.File]::WriteAllText(
    $OutputPath,
    $generated,
    [System.Text.UTF8Encoding]::new($false))

Write-Output "SIMUL_MARKET_CALENDAR_GENERATED dates=$($dates.Count) bytes=$($bytes.Length) sha256=$sourceHash"
